services:
  postgres:
    image: postgres:16@sha256:e0806e830dc71046e0f67da6f77040acc5321f0664cf2530f138148c7998326e
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: hui@mail.ru
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    depends_on:
      - postgres
    ports:
      - "5050:80"