---
- name: update apt list
  apt:
    update_cache: yes

- name: Install python
  ansible.builtin.apt:
    name:
      - python3
    state: present

- name: Install pip
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present